name: Delete Webradio
description: Delete a new webradio
title: "[Delete Webradio]: "
labels: ["DeleteWebradio"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a deletion!
  - type: input
    id: deleteWebradio
    attributes:
      label: Webradio to delete
      description: The stream uri, e.g. http://119.15.96.188/stream2.mp3
    validations:
      required: true
  - type: dropdown
    id: justification
    attributes:
      label: Justification
      description: Why?
      options:
        - No longer available
        - Illegal stream
        - Duplicate
        - other (please describe)
    validations:
      required: true
  - type: textarea
    id: justificationText
    attributes:
      label: Other
      description: Why?
    validations:
      required: false
