name: Modify Webradio
description: Modify a webradio
title: "[Modify Webradio]: "
labels: ["ModifyWebradio"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a modification!
  - type: input
    id: mdofiyName
    attributes:
      label: Webradio to modify
      description: The name of the webradio to modify.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Add the new values, leave unchanged fields empty.
  - type: input
    id: name
    attributes:
      label: New webradio Name
      description: The name of the webradio.
    validations:
      required: false
  - type: input
    id: streamuri
    attributes:
      label: New stream URI
      description: The URI of the stream - not the playlist.
    validations:
      required: false
  - type: input
    id: genre
    attributes:
      label: New genres
      description: A comma separated list of genres.
    validations:
      required: false
  - type: input
    id: homepage
    attributes:
      label: New homepage
      description: The homepage of the webradio.
    validations:
      required: false
  - type: input
    id: image
    attributes:
      label: Image
      description: The radiostation logo.
    validations:
      required: false
  - type: input
    id: country
    attributes:
      label: New country
      description: The country e.g. Germany.
    validations:
      required: false
  - type: input
    id: language
    attributes:
      label: New language
      description: The language of the webradio.
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: New description
      description: A short description (one-liner).
    validations:
      required: false
