name: Modify Webradio
description: Modify a webradio
title: "[Modify Webradio]: "
labels: ["ModifyWebradio"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a modification!
  - type: input
    id: modifyWebradio
    attributes:
      label: Webradio to modify
      description: The stream uri, e.g. http://119.15.96.188/stream2.mp3
    validations:
      required: true
  - type: textarea
    id: note
    attributes:
      label: Note
      description: Short description of the modification.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Add the new values, leave unchanged fields empty.
  - type: input
    id: name
    attributes:
      label: New webradio Name
      description: The name of the webradio.
    validations:
      required: false
  - type: input
    id: streamuri
    attributes:
      label: New stream URI
      description: The URI of the stream - not the playlist.
    validations:
      required: false
  - type: input
    id: genre
    attributes:
      label: New genres
      description: A comma separated list of genres.
    validations:
      required: false
  - type: input
    id: homepage
    attributes:
      label: New homepage
      description: The homepage of the webradio.
    validations:
      required: false
  - type: input
    id: image
    attributes:
      label: Image
      description: A link to the radiostation logo or the already downloaded filename.
    validations:
      required: false
  - type: input
    id: country
    attributes:
      label: New country
      description: The country e.g. Germany.
    validations:
      required: false
  - type: input
    id: region
    attributes:
      label: New region
      description: The region, e.g. Bayern.
    validations:
      required: false
  - type: input
    id: language
    attributes:
      label: New language
      description: The language of the webradio.
    validations:
      required: false
  - type: input
    id: codec
    attributes:
      label: New codec
      description: The codec of the stream, e. g. MP3, AAC, ...
    validations:
      required: false
  - type: input
    id: bitrate
    attributes:
      label: New bitrate
      description: The birate of the stream in kbit.
    validations:
      required: false
  - type: input
    id: description
    attributes:
      label: New description
      description: A short description (one-liner).
    validations:
      required: false
