# This workflow creates the publish files

name: imageChecks

# Controls when the workflow will run
on:
  #run it daily
  schedule:
  - cron: "6 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checks:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Check images
        run: ./build.sh check_images_all

      - name: Add, commit and push
        uses: EndBug/add-and-commit@v7.5.0
        with:
          add: docs/db sources
          message: dbChecks
          pull: NO-PULL
          push: true
