# This workflow creates the publish files

name: createWebradioIndex

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the master branch and sources root folder
  push:
    branches: [ master ]
    paths:
    - 'sources/**'
  #run it daily
  schedule:
  - cron: "6 3 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create the webradio publish files
        run: ./build.sh create

      - name: Add, commit and push
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: docs/db sources
          message: Update db index
          push: true
