# This workflow creates the publish files

name: syncMoode

# Controls when the workflow will run
on:
  #run it weekly - each monday
  schedule:
  - cron: "6 0 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  syncMoode:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install prerequisites
        run: sudo apt install -y csvkit

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Syncs the moode audio webradio files
        run: ./build.sh sync_moode

      - name: Add, commit and push
        uses: EndBug/add-and-commit@v9.0.1
        with:
          add: docs/db sources
          message: Update db index
          push: true
