name: webradioFromIssue

on:
  issues:
    types: [labeled]

jobs:
  addradio:
    if: ${{ github.event.label.name == 'MergeNewWebradio' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y --no-install-recommends imagemagick

      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add-webradio.yml

      - name: Creating webradio m3u
        run: |
          cat > issue.json << EOL
          ${{ steps.issue-parser.outputs.jsonString }}
          EOL
          ./build.sh add_radio_from_json issue.json
          rm issue.json

      - name: Add, commit and push
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: sources docs/db
          message: "webradioFromIssue - addradio #${{ github.event.issue.number }}"
          pull: NO-PULL
          push: true

      - uses: peter-evans/close-issue@v2
        with:
          comment: Merged!

  modifyradio:
    if: ${{ github.event.label.name == 'MergeModifyWebradio' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/modify-webradio.yml

      - name: Modifying webradio m3u
        run: |
          cat > issue.json << EOL
          ${{ steps.issue-parser.outputs.jsonString }}
          EOL
          ./build.sh modify_radio_from_json issue.json
          rm issue.json

      - name: Add, commit and push
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: sources docs/db mappings
          message: "webradioFromIssue - modifyradio #${{ github.event.issue.number }}"
          pull: NO-PULL
          push: true

      - uses: peter-evans/close-issue@v2
        with:
          comment: Merged!

  deleteradio:
    if: ${{ github.event.label.name == 'MergeDeleteWebradio' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/delete-webradio.yml

      - name: Deleting webradio m3u
        run: |
          cat > issue.json << EOL
          ${{ steps.issue-parser.outputs.jsonString }}
          EOL
          ./build.sh delete_radio_from_json issue.json
          rm issue.json

      - name: Add, commit and push
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: sources docs/db mappings
          message: "webradioFromIssue - deleteradio #${{ github.event.issue.number }}"
          pull: NO-PULL
          push: true

      - uses: peter-evans/close-issue@v2
        with:
          comment: Merged!

  addAlternateStream:
    if: ${{ github.event.label.name == 'MergeAddAlternateStream' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add-alternate-stream.yml

      - name: Add alternate stream
        run: |
          cat > issue.json << EOL
          ${{ steps.issue-parser.outputs.jsonString }}
          EOL
          ./build.sh add_alternate_stream_from_json issue.json
          rm issue.json

      - name: Add, commit and push
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: sources docs/db
          message: "webradioFromIssue - addAlternateStream #${{ github.event.issue.number }}"
          pull: NO-PULL
          push: true

      - uses: peter-evans/close-issue@v2
        with:
          comment: Merged!

  deleteAlternateStream:
    if: ${{ github.event.label.name == 'MergeDeleteAlternateStream' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/delete-alternate-stream.yml

      - name: Delete alternate stream
        run: |
          cat > issue.json << EOL
          ${{ steps.issue-parser.outputs.jsonString }}
          EOL
          ./build.sh delete_alternate_stream_from_json issue.json
          rm issue.json

      - name: Add, commit and push
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: sources docs/db
          message: "webradioFromIssue - deleteAlternateStream #${{ github.event.issue.number }}"
          pull: NO-PULL
          push: true

      - uses: peter-evans/close-issue@v2
        with:
          comment: Merged!
